import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserCircle, faPlusCircle, faTshirt, faCreditCard, faCoins,
faGraduationCap, faCar, faMobileAlt, faPlane, faStar, faShower,
faShoppingBasket, faHome, faHospital, faMoneyBill, faHandHoldingHeart,
faQuestion, faCarSide, faBus, faFilm, faUtensils, faWifi, faProcedures,
faLandmark, faPlug} from '@fortawesome/free-solid-svg-icons'

library.add(
    faUserCircle,
    faPlusCircle,
    faCreditCard,
    faTshirt,
    faGraduationCap,
    faQuestion,
    faShoppingBasket,
    faMoneyBill,
    faUtensils,
    faWifi,
    faCar,
    faProcedures,
    faLandmark,
    faShower,
    faPlug,
    faCarSide,
    faBus,
    faHome,
    faHospital,
    faStar,
    faHandHoldingHeart,
    faFilm,
    faPlane,
    faMobileAlt,
    faCoins);